name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - main
    tags:
      - 'v*'
  schedule:
    # 1st Monday of each month
    - cron: '30 5 1-7 * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print Variables (env)
        run: env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          pull: true
          push: true
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postfixadmin:latest
